Traceback (most recent call last):
  File "main.py", line 47, in <module>
  File "main.py", line 39, in main
  File "wx\_core.pyo", line 8081, in __init__
  File "wx\_core.pyo", line 7974, in __init__
  File "wx\_misc.pyo", line 6216, in SetInstallPrefix
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 3: ordinal not in range(128)
Traceback (most recent call last):
  File "main.py", line 47, in <module>
  File "main.py", line 39, in main
  File "wx\_core.pyo", line 8081, in __init__
  File "wx\_core.pyo", line 7974, in __init__
  File "wx\_misc.pyo", line 6216, in SetInstallPrefix
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 3: ordinal not in range(128)
Traceback (most recent call last):
  File "main.py", line 47, in <module>
  File "main.py", line 39, in main
  File "wx\_core.pyo", line 8081, in __init__
  File "wx\_core.pyo", line 7974, in __init__
  File "wx\_misc.pyo", line 6216, in SetInstallPrefix
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 3: ordinal not in range(128)
